const vehicleData = [
    {
      id: 1,
      name: "LEOPARD 2PL MBT",
      user: null,
      category: "BATTLE TANKS",
      description: "Leopard 2PL is a third generation Main Battle Tank,made in cooperation with Polish Armaments Group and Rheinmetall Landsysteme.The tank is designed to master and maintain the area,and support fire from deck weapons of mechanized and motorized subunits,in all weather conditions,both during the day and at night.As a result of the work,two versions of the vehicles were developed: the Leopard 2PL version,which is currently supplied to the military.",
      image: "https://i.ibb.co/wJQ4Q4R/Leopard-2-PL-tank10.jpg",
      price: "15000000",
      quantity:20,
      sold:27,
      supplierName: "Polish Armaments Group"
    },
    {
      id: 2,
      name: "MIKOYAN MIG-29",
      user: null,
      category: "FIGHTER JETS",
      description: "The Mikoyan MiG-29 is a twin-engine fighter aircraft designed in the Soviet Union.Developed by the Mikoyan design bureau as an air superiority fighter during the 1970s,the MiG-29,along with the larger Sukhoi Su-27,was developed to counter new U.S.fighters such as the McDonnell Douglas F-15 Eagle and the General Dynamics F-16 Fighting Falcon.The MiG-29 entered service with the Soviet Air Forces in 1982.",
      image: "https://i.ibb.co/3z62H6H/mikoyan-mig29.jpg",
      price: "548000000",
      quantity:50,
      sold:56,
      supplierName: "Mikoyan"
    },
    {
      id: 3,
      name: "TYPE 053H FRIGATE",
      user: null,
      category: "BATTLE SHIPS",
      description: "The PLAN retired many older frigates in the 1970s,and the No.701 Institute developed the Type 053H as a replacement.The initial design was armed with four SY-1 anti-ship missiles in two twin-missile box launchers,two single 100 mm.guns,six twin 37mm guns,depth charges and short-range ASW rockets.The Type 053H received the NATO codename Jianghu-I.The first was constructed by the Hudong Shipyard and entered service in the mid-1970s.",
      image: "https://i.ibb.co/jHFczpD/type-05-H-frigate.jpg",
      price: "5600000000",
      quantity:5,
      sold:30,
      supplierName: "Naresuan"
    },
    {
      id: 4,
      name: "BAYRAKTAR TB2",
      user: null,
      category: "UAV DRONES",
      description: "The Bayraktar TB2 is a medium-altitude long-endurance unmanned combat aerial vehicle capable of remotely controlled or autonomous flight operations.It is manufactured by the Turkish company Baykar Makina Sanayi ve Ticaret A.Ş.,primarily for the Turkish Armed Forces.The aircraft are monitored and controlled by an aircrew in a ground control station,including weapons employment.The development of the UAV has been largely credited.",
      image: "https://i.ibb.co/SdfwwRJ/Bayraktar-TB2.jpg",
      price: "5000000",
      quantity:250,
      sold:100,
      supplierName: "Baykar"
    },
    {
      id: 5,
      name: "HQ-22 SAM",
      user: null,
      category: "SAM SYSTEMS",
      description: "A typical HQ-22 battery includes one radar vehicle and three transporter erector launchers equipped with four missiles each.Each battery can reportedly engage six aerial targets simultaneously.The missile system has been widely compared to the United States' Patriot and Russia's mobile long range S-300 surface-to-air missile system.Although it has a shorter range than S-300 variants such as the S-300PMU-2.",
      image: "https://i.ibb.co/60w5Q0V/hq-22.jpg",
      price: "4052200",
      quantity:150,
      sold:55,
      supplierName: "CASIC"
    },
    {
      id: 6,
      name: "AKULA CLASS SUBMARINE",
      user: null,
      category: "BATTLE SUBMARINES",
      description: "The Akula class,Soviet designation Project 971 Shchuka-B are a series of nuclear-powered attack submarines first deployed by the Soviet Navy in 1986.There are four sub-classes or flights of Shchuka-B,consisting of the original seven Project 971 boats,commissioned between 1984 and 1990; six Project 971Is,commissioned between 1991 and 2009; one Project 971U,commissioned in 1995 and one Project 971M,commissioned in 2001.",
      image: "https://i.ibb.co/RcbJGG9/akula-class.jpg",
      price: "870000000",
      quantity:10,
      sold:50,
      supplierName: "Severodvinsk"
    },
    {
      id: 7,
      name: "BLACK EAGLE MBT",
      user: null,
      category: "BATTLE TANKS",
      description: "Development started during the 1980s,when the design bureau of the Leningrad Kirov Plant developed a new design based on the stretched T-80U chassis.Later,when the bureau closed,the documentation was transferred to KBTM in Omsk.A mock-up of the Black Eagle was first demonstrated at the VTTV arms exposition in Omsk,in September 1997,making a single brief pass,far from the reviewing stands.The tank appeared to be a elongated T-80U hull.",
      image: "https://i.ibb.co/VNV17RH/black-eagle-tank9.jpg",
      price: "78225000",
      quantity:45,
      sold:200,
      supplierName: "Omsktransmash"
    },
    {
      id: 8,
      name: "VT-4 MBT",
      user: null,
      category: "BATTLE TANKS",
      description: "The VT-4 has a 125mm smoothbore cannon capable of firing APFSDS,HESH,HEAT and HE rounds and guided missiles.There is also a remote weapon station on the turret armed with a 12.7 mm heavy machine gun.The fire control system has hunter-killer capabilities,laser rangefinder,panoramic sight and a third generation thermal imaging system.According to the chief designer,the APFSDS used by VT-4 can reach 700mm penetration which is enough to penetrate any armoured target.",
      image: "https://i.ibb.co/dQpYzyV/VT-4-tank8.jpg",
      price: "78000000",
      quantity:52,
      sold:20,
      supplierName: "Norinco"
    },
    {
      id: 9,
      name: "KERRAR MBT",
      user: null,
      category: "BATTLE TANKS",
      description: "The main armament of the Karrar consists of a 125 mm smoothbore gun fitted with a fume extractor and a thermal sleeve.A remotely operated weapon station armed with a 12.7 mm machine gun is mounted on the roof of the turret.The main gun is able to fire anti-tank laser-guided missiles.An autoloader is also installed,removing the need of a loader.",
      image: "https://i.ibb.co/6yK2S68/kerrar-tank7.jpg",
      price: "50000000",
      quantity:45,
      sold:40,
      supplierName: "IRGC"
    },
    {
      id: 10,
      name: "F-22 RAPTOR",
      user: null,
      category: "FIGHTER JETS",
      description: "As the program moved to full-scale development,or Engineering & Manufacturing Development,the production version had notable differences from the YF-22,despite having a similar configuration.The wing's leading edge sweep angle was decreased from 48° to 42°,while the vertical stabilizers were shifted rearward and decreased in area by 20%.To improve pilot visibility,the canopy was moved forward 7 inches and the engine intakes moved rearward 14 inches.",
      image: "https://i.ibb.co/vJPXTWv/f22-raptor.jpg",
      price: "500000000",
      quantity:50,
      sold:30,
      supplierName: "Lockheed Martin Aeronautics"
    },
    {
      id: 11,
      name: "SUKHOI SU-57",
      user: null,
      category: "FIGHTER JETS",
      description: "The Sukhoi Su-57 is a single-seat,twin-engine stealth multirole fighter aircraft developed by Sukhoi.The aircraft is the product of the PAK FA Perspektivnyy Aviatsionnyy Kompleks Frontovoy Aviatsii,lit.prospective aeronautical complex of front-line air forces fighter programme,which is intended to be the basis for a family of stealth combat aircraft.",
      image: "https://i.ibb.co/XkRJJvs/su-57.jpg",
      price: "20000000",
      quantity:65,
      sold:5,
      supplierName: "Komsomolsk-on-Amur Aircraft Plant"
    },
    {
      id: 12,
      name: "F-35 LIGHTNING II",
      user: null,
      category: "FIGHTER JETS",
      description: "The Lockheed Martin F-35 Lightning II is an American family of single-seat,single-engine,all-weather stealth multirole combat aircraft that is intended to perform both air superiority and strike missions.It is also able to provide electronic warfare and intelligence,surveillance,and reconnaissance capabilities.Lockheed Martin is the prime F-35 contractor,with principal partners Northrop Grumman and BAE Systems.The aircraft has three main variants.",
      image: "https://i.ibb.co/Tm4hYpv/f-35-lightning.jpg",
      price: "405000000",
      quantity:85,
      sold:20,
      supplierName: "Lockheed Martin"
    },
    {
      id: 13,
      name: "CASTLE CLASS CORVETTE",
      user: null,
      category: "BATTLE SHIPS",
      description: "The Castle class was designed by David K.Brown and was intended as a series of six offshore patrol vessels for the Royal Navy,designed in response to criticism of the previous Island class for insufficient speed,sub-optimal sea-keeping and lack of a flight deck for rescue helicopters.In the event,only two ships were built,HMS Leeds Castle and HMS Dumbarton Castle.Both vessels were built by Hall Russell in Aberdeen,Scotland.",
      image: "https://i.ibb.co/wzHg56D/castle-class-corvette.png",
      price: "1020000000",
      quantity:10,
      sold:5,
      supplierName: "Hall,Russell & Company"
    },
    {
      id: 14,
      name: "HAMILTON CLASS FRIGATE",
      user: null,
      category: "BATTLE SHIPS",
      description: "The Hamilton-class cutters were designed to be a highly versatile platform capable of performing various operations,including maritime law enforcement,search and rescue,oceanographic research,and defense operations.Because of their endurance and capabilities,the Hamilton-class cutters commonly deployed with Carrier Battle Groups.They were built with a welded steel hull and aluminum superstructure.",
      image: "https://i.ibb.co/12FLhQt/hamilton-class-frigate.jpg",
      price: "3540000000",
      quantity:15,
      sold:12,
      supplierName: "Avondale Shipyards"
    },
    {
      id: 15,
      name: "TYPE 056 CORVETTE",
      user: null,
      category: "BATTLE SHIPS",
      description: "The Type 056 is a class of corvette deployed by the Chinese People's Liberation Army Navy.They replace older patrol craft and some of the Type 053H frigates.The first Type 056 entered service in February 2013.An anti-submarine warfare variant,commonly known as Type 056A,has also entered service.Following construction of the Aba in December 2019,China ceased building of Type 056 corvettes to focus on procuring bigger warships for high sea missions.",
      image: "https://i.ibb.co/9gNN0qw/type-056-corvette.jpg",
      price: "700000000",
      quantity:30,
      sold:8,
      supplierName: "Hudong-Zhonghua Shipbuilding"
    },
    {
      id: 16,
      name: "CAIG WING LOONG",
      user: null,
      category: "UAV DRONES",
      description: "The Chengdu Pterodactyl also known as Wing Loong,is a Medium-Altitude Long-Endurance unmanned aerial vehicle,developed by the Chengdu Aircraft Industry Group in the People's Republic of China.Intended for use as a surveillance and aerial reconnaissance platform,the Pterodactyl I is capable of being fitted with air-to-surface weapons for use in an unmanned combat aerial vehicle role.Based on official marketing material released by CADI.",
      image: "https://i.ibb.co/xCsWNbt/wing-loogn.jpg",
      price: "4502220",
      quantity:300,
      sold:2,
      supplierName: "Chengdu Aircraft Industry"
    },
    {
      id: 17,
      name: "KAMAN 22",
      user: null,
      category: "UAV DRONES",
      description: "Kaman 22 (UAV) is an Iranian wide-body unmanned combat aerial vehicle unveiled on the 24th of February,2021 by the Islamic republic of Iran Air Force.It is said to be the country's first wide-body drone.The range of the Kaman 22 is approximately 3,000 km (1,900 mi) and it can carry 300 kg of explosives.According to IRIAF commander Aziz Nasirzadeh,the Kaman 22 is the first domestically-manufactured wide-body combat drone in the country.",
      image: "https://i.ibb.co/BwmKKkh/Kaman-22.jpg",
      price: "2500000",
      quantity:350,
      sold:150,
      supplierName: "IRIAF"
    },
    {
      id: 18,
      name: "SHAHED 129",
      user: null,
      category: "UAV DRONES",
      description: "The Shahed 129 is an Iranian single-engine medium-altitude long-endurance unmanned combat aerial vehicle (UCAV) designed by Shahed Aviation Industries for the Islamic Revolutionary Guard Corps.The Shahed 129 is capable of combat and reconnaissance missions and has an endurance of 24 hours; it is similar in size,shape and role to the American MQ-1 Predator and is widely considered as one of the most capable drones in Iranian service.",
      image: "https://i.ibb.co/BZrgX8n/Shahed-129.jpg",
      price: "4500000",
      quantity:400,
      sold:10,
      supplierName: "HESA"
    },
    {
      id: 19,
      name: "YA ZAHRA ADS",
      user: null,
      category: "SAM SYSTEMS",
      description: "Ya Zahra is an Iranian unlicensed copy of the HQ-7,itself an unlicensed copy of the French Crotale missile short-range air defense system.The system entered production in 2013.The Ya Zahra differs from Irans Raad in being a short-range air defense system.Iranian sources say it is able to form a missile defense network.This system was successfully tested in Defenders of Velayat Skies 4 air defense drills.",
      image: "https://i.ibb.co/qxbkGkz/ya-zahra.jpg",
      price: "452100",
      quantity:250,
      sold:10,
      supplierName: "IRIADF"
    },
    {
      id: 20,
      name: "AKASH SAM",
      user: null,
      category: "SAM SYSTEMS",
      description: "Akash is a medium-range mobile surface-to-air missile system developed by the Defence Research and Development Organisation and produced by Bharat Dynamics Limited.Surveillance and Fire control radar,tactical control and command center and missile launcher are developed by Bharat Electronics,Tata Power Strategic Engineering Division and Larsen & Toubro.The Akash missile system can target aircraft up to 30 km away.",
      image: "https://i.ibb.co/8jKybXf/akash.jpg",
      price: "500000",
      quantity:750,
      sold:10,
      supplierName: "Bharat Dynamics Limited"
    },
    {
      id: 21,
      name: "HISAR SAM",
      user: null,
      category: "SAM SYSTEMS",
      description: "The HISAR is a family of short,medium and long-range surface-to-air missile systems being developed by Roketsan and Aselsan since 2007.The missiles are developed by Roketsan,while most sensors and electronics are developed by Aselsan.The missile family consists of the short range HİSAR-A,medium range HISAR-O,the 100 km long range HISAR-U and the 150 km air defence system SIPER.Missile seeker of HİSAR-A and HISAR-O is infrared homing.",
      image: "https://i.ibb.co/wcJsvMd/hisar.jpg",
      price: "450000",
      quantity:562,
      sold:10,
      supplierName: "ASELSAN and ROKETSAN"
    },
    {
      id: 22,
      name: "ASTUTE CLASS SUBMARINE",
      user: null,
      category: "BATTLE SUBMARINES",
      description: "The Astute class is the latest class of nuclear-powered fleet submarines in service with the Royal Navy.The boats are being constructed by BAE Systems Submarines at Barrow-in-Furness.Seven boats will be constructed: the first of class,Astute,was launched by Camilla,Duchess of Cornwall,in 2007,commissioned in 2010,and declared fully operational in May 2014.The Astute class is the replacement for the Trafalgar-class fleet submarines in Royal Navy service.",
      image: "https://i.ibb.co/mzJr0sJ/astute-class.jpg",
      price: "100000000",
      quantity:5,
      sold:10,
      supplierName: "BAE Systems Submarines"
    },
    {
      id: 23,
      name: "BARRACUDA CLASS SUBMARINE",
      user: null,
      category: "BATTLE SUBMARINES",
      description: "The Barracuda clas is a nuclear attack submarine,designed by the French shipbuilder Naval Group for the French Navy.It is intended to replace the Rubis-class submarines.Construction began in 2007 and the first unit was commissioned on 6 November 2020.Full operational capability is not anticipated until 2022.",
      image: "https://i.ibb.co/MkRZnsJ/barracuda-class.jpg",
      price: "200000000",
      quantity:8,
      sold:10,
      supplierName: "Naval Group "
    },
    {
      id: 24,
      name: "SEAWOLF CLASS SUBMARINE",
      user: null,
      category: "BATTLE SUBMARINES",
      description: "The Seawolf class is a class of nuclear-powered fast attack submarines in service with the United States Navy.The class was the intended successor to the Los Angeles class,and design work began in 1983.A fleet of 29 submarines was to be built over a ten-year period,but that was reduced to 12 submarines.The end of the Cold War and budget constraints led to the cancellation of any further additions to the fleet in 1995.",
      image: "https://i.ibb.co/Wc1bWnh/seawolf-class.jpg",
      price: "500000000",
      quantity:10,
      sold:10,
      supplierName: "General Dynamics Electric Boat"
    },
    {
      id: 25,
      name: "LECLERC MBT",
      user: null,
      category: "BATTLE TANKS",
      description: "The Leclerc tank is a main battle tank built by Nexter Systems of France.It was named in honor of General Philippe Leclerc de Hauteclocque,who led the French element of the drive towards Paris while in command of the Free French 2nd Armoured Division in World War II.The designation while very popular is incorrect.",
      image: "https://i.ibb.co/1zKVyD5/leclerc-tank6.jpg",
      price: "65000000",
      quantity:32,
      sold:10,
      supplierName: "Direction des Armements"
    },
    {
      id: 26,
      name: "CHENGDU J-20",
      user: null,
      category: "FIGHTER JETS",
      description: "The Chengdu J-20,also known as Mighty Dragon,is a twinjet all-weather stealth fighter aircraft developed by China's Chengdu Aerospace Corporation for the People's Liberation Army Air Force.The J-20 is designed as an air superiority fighter with precision strike capability;it descends from the J-XX program of the 1990s.The J-20 made its maiden flight on 11 January 2011,and was officially revealed at the 2016 China International Aviation & Aerospace Exhibition.",
      image: "https://i.ibb.co/pQzwDTq/Chengdu-J-20.jpg",
      price: "56400000",
      quantity:46,
      sold:10,
      supplierName: "Chengdu Aerospace Corporation"
    },
    {
      id: 27,
      name: "PADMA CLASS PATROL VESSEL",
      user: null,
      category: "BATTLE SHIPS",
      description: "The launch of the indigenous warship paved the way for the Bangladesh Navy to soon deploy its own design.Built at the Khulna Shipyard,the design is an offshore patrol vessel that displaces 350 tonnes.The ships are 165.35 feet long,with a beam of 24.61 ft and a draught of 13.45 ft.The ships can carry out missions lasting up to seven days at a time.They have a complement of 45 personnel with a top speed of 23 knots.",
      image: "https://i.ibb.co/2yVqYPY/padma-class-patrol-vessel.jpg",
      price: "56000000",
      quantity:150,
      sold:10,
      supplierName: "Khulna Shipyard"
    },
    {
      id: 28,
      name: "TAI ANKA",
      user: null,
      category: "UAV DRONES",
      description: "The TAI Anka is a family of unmanned aerial vehicles developed by Turkish Aerospace Industries primarily for the Turkish Air Force.Envisioned in the early 2000s for aerial surveillance and reconnaissance missions,Anka has evolved into a modular platform with synthetic aperture radar,precise weapons and satellite communication.The basic version,Anka-A,was classified as a medium-altitude long-endurance unmanned aerial vehicle for reconnaissance missions.",
      image: "https://i.ibb.co/djSPMm4/anka.jpg",
      price: "3550000",
      quantity:200,
      sold:10,
      supplierName: "Turkish Aerospace Industries"
    },
    {
      id: 29,
      name: "RAPIER SAM",
      user: null,
      category: "SAM SYSTEMS",
      description: "Rapier is a surface-to-air missile developed for the British Army to replace their towed Bofors 40/L70 anti-aircraft guns.The system is unusual as it uses a manual optical guidance system,sending guidance commands to the missile in flight over a radio link.This results in a high level of accuracy,therefore a large warhead is not required.Entering service in 1971,it eventually replaced all other anti-aircraft weapons in British Army service.",
      image: "https://i.ibb.co/6g4msG5/rapier-missile.jpg",
      price: "600000",
      quantity:300,
      sold:10,
      supplierName: "British Aircraft Corporation"
    },
    {
      id: 30,
      name: "TRAFALGAR CLASS SUBMARINE",
      user: null,
      category: "BATTLE SUBMARINES",
      description: "The Trafalgar class is a class of nuclear-powered fleet submarines in service with the Royal Navy,and the successor to the Swiftsure class.Like the majority of Royal Navy nuclear submarines,all seven boats were constructed at Barrow-in-Furness shipyard,Cumbria.With only one boat remaining active and in commission and six retired from the seven originally in service,the class makes up part of the Royal Navy's nuclear-powered hunter-killer submarine force.",
      image: "https://i.ibb.co/Mh18zTB/trafalgar-class.jpg",
      price: "548000000",
      quantity:10,
      sold: 10,
      supplierName: "Vickers Shipbuilding"
    }
  ]
  